config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users do
    resources :images, only: [:index]
  end
  resources :images, only: [:new, :create, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin
      can :dashboard
    end
    if user.supervisor_role?
      can :manage, User
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  
  has_attached_file :image, 
  :styles => {
  	:thumb    => ['100x100#',  :jpg, :quality => 50],
  	:preview  => ['480x480#',  :jpg, :quality => 50],
  	:large    => ['600>',      :jpg, :quality => 80],
  	:retina   => ['1200>',     :jpg, :quality => 50]
  	},
  :url => ":s3_domain_url",
  :path => ":user_id/:id.:style.:extension"
  
  validates_attachment :image,
    	:presence => true,
    	:size => { :in => 0..2.megabytes },
    	:content_type => { :content_type => /^image\/(jpeg|png|gif|tiff|ico)$/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :images, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.json
  def index
    @images = User.find(params[:user_id]).images
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # POST /images
  # POST /images.json
  def create
    @image = current_user.images.build(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to user_images_path(current_user), notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    Image.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(image) do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/index.html.erb
<%= link_to 'New Image', new_image_path %>

<% sizer = "grid-sizer" %>
<div class="grid">
  <% @images.each do |image| %>
    <div class="grid-item <%= sizer %> col-xs-12 col-sm-6 col-md-3 col-lg-2"><% sizer = "" %>
      <div class="panel panel-default">
        <div class="panel-body">
          <img src="<%= image.image.url(:preview) %>" onclick="showImage('<%= image.image.url(:preview) %>', '<%= image.image.url(:large) %>');"/>
        </div>
      </div>
    </div>
  <% end %>
  
  <div id="largeImgPanel" onclick="this.style.display='none'">
    <img id="largeImg" style="height:100%; margin:0; padding:0;" />
  </div>
</div>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Rails bootstrap", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>
<% if current_user.nil? %>
	<li class='nav-item'><%= link_to new_user_session_path, class: 'nav-link login-button' do %>Sign in<% end %></li>
	<li class='nav-item'><%= link_to('Register', new_user_registration_path, class: 'nav-link')  %></li>
  <li class='nav-item'><%= link_to('Login', new_user_session_path, class: 'nav-link')  %></li>
<% else %>
	<li class='nav-item'><%= link_to root_path, class: 'nav-link login-button' do %>Go to App<% end %></li>
	<li class='nav-item'><%= link_to user_images_path(current_user), class: 'nav-link login-button' do %>View Your Images<% end %></li>
	<li class='nav-item'><%= link_to('Edit registration', edit_user_registration_path, class: 'nav-link') %></li>
  <li class='nav-item'><%= link_to('Logout', destroy_user_session_path, class: 'nav-link', :method => :delete) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Thepcgame" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Thepcgame" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    
    <script type="text/javascript">
      function showImage(smSrc, lgSrc) {
        document.getElementById('largeImg').src = smSrc;
        showLargeImagePanel();
        unselectAll();
        setTimeout(function() {
            document.getElementById('largeImg').src = lgSrc;
        }, 1)
      }
      function showLargeImagePanel() {
          document.getElementById('largeImgPanel').style.display = 'block';
      }
      function unselectAll() {
        if(document.selection)
          document.selection.empty();
        if(window.getSelection)
          window.getSelection().removeAllRanges();
      }
    </script>
    
    <style type="text/css">
      #largeImgPanel {
        text-align: center;
        display: none;
        position: fixed;
        z-index: 100;
        top: 0; left: 0; width: 100%; height: 100%;
        background-color: rgba(100,100,100, 0.5);
      }
    </style>
    
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>